# Modified from https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml

os: Visual Studio 2015
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --release --verbose

artifacts:
  - path: target\release\meshlite.dll
    name: meshlite.dll

  - path: target\release\meshlite.dll.lib
    name: meshlite.dll.lib

deploy:
  release: meshlite-unstable
  description: 'Unstable release for test purpose only'
  provider: GitHub
  auth_token:
    secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
  artifact: meshlite.dll.lib,meshlite.dll
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only