# Modified from https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml

os: Visual Studio 2015
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
      platform: x64
    - channel: stable
      target: i686-pc-windows-msvc
      platform: x86

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cd ffi
  - cargo build --release --verbose
  - cd ..

after_test:
  - 7z a meshlite_unstable_vc14_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\ffi\include\meshlite.h
  - 7z a meshlite_unstable_vc14_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\ffi\target\release\meshlite_ffi.dll
  - 7z a meshlite_unstable_vc14_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\ffi\target\release\meshlite_ffi.dll.lib

artifacts:
  - path: '*.zip'
    name: platform_zips

deploy:
  release: meshlite-unstable
  description: 'Unstable release for test purpose only. The source code is attached when this release first created, and it is not get updated while the binary been replaced.'
  force_update: true
  provider: GitHub
  auth_token:
    secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
  artifact: platform_zips
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
