# Modified from https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml

os: Visual Studio 2015
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --release --verbose

after_test:
  - 7z a meshlite_unstable_$(platform).zip %APPVEYOR_BUILD_FOLDER%\target\release\meshlite.dll
  - 7z a meshlite_unstable_$(platform).zip %APPVEYOR_BUILD_FOLDER%\target\release\meshlite.dll.lib

artifacts:
  - path: meshlite_$(platform).zip
    name: meshlite_$(platform).zip

deploy:
  release: meshlite-unstable
  description: 'Unstable release for test purpose only'
  force_update: true
  provider: GitHub
  auth_token:
    secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
  artifact: meshlite_$(platform).zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only